services:
  app:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    # network_mode: "host"
    env_file: 
      - .env
    deploy:
      resources:
        limits:
          cpus: "3" # Using 3 Cores Maximum
          memory: 4g # Using 4GB Memory